name = "portfolirarnext"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".next"

[build]
command = "npm run build"

[[build.upload]]
format = "directory"
dir = ".next"
exclude = [
  "cache/**",
  "**/*.map",
  "**/node_modules/**",
  "**/.git/**"
]
